### ISSUE TITLE
File Manager UI Flash

### ISSUE THREAD

**Issue by ares1010** [ClubCaribe/DataIsland#2]
Occurrence: Selecting "File Manager" from Nav or refreshing the "File Manager" page

Issue: All underlying UI elements load and flash on screen before the page finishes loading. This is currently occurring with no files present and files present.

Solution: Fix onload behavior.

![screen shot 2015-03-15 at 11 19 54 am](https://cloud.githubusercontent.com/assets/5697250/6657743/e52a7116-cb11-11e4-9224-cc8a10506554.png)

**Comment by indigokrk** [comment]
panel now is invisible during page load. This should prevent page flickering
